define(['./options-test'
, './client/database-test'
, './client/databases-test'
, './client/database-names-test'
, './client/collection-test'
, './client/options-test'
, './client/read-preference-test'
, './client/write-concern-test'
, './database/self-connected-test'
, './database/collection-test'
, './database/collection-names-test'
, './database/collections-test'
, './database/command-test'
, './database/create-collection-test'
, './database/drop-test'
, './collection/self-connected-test'
, './collection/insert-many-test'
, './collection/insert-one-test'
, './collection/count-test'
, './collection/commands1-test'
, './collection/commands2-test'
, './collection/create-index-test'
, './collection/create-indexes-test'
, './collection/reindex-test'
, './collection/list-indexes-test'
, './collection/delete-one-test'
, './collection/delete-many-test'
, './collection/read-preference-test'
, './collection/write-concern-test'
, './collection/rename-test'
, './collection/explain-test'
, './collection/stats-test'
, './collection/bulk-write-test'
, './collection/update-one-test'
, './collection/update-many-test'
, './collection/save-test'
, './collection/replace-one-test'
, './collection/map-reduce-test'
, './collection/group-test'
, './collection/geo-near-test'
, './collection/geo-haystack-test'
, './collection/find-one-and-update-test'
, './collection/find-one-and-replace-test'
, './collection/find-one-and-delete-test'
, './collection/find-test'
, './collection/find-one-test'
, './collection/distinct-test'
, './collection/aggregate-test'
    ], function () {
    var tests = [];
    for (var i = 0; i < arguments.length - 1; i++)
        tests.push(new arguments[i]());
    return tests;
});